#5 Spelling mistake fixes
wearecodenation/master21-git101 pull request #123
Opened 2021-01-28 11:14 UTC by JakeyD11

2021-01-28 11:22 UTC, carys23 approved these changes

2021-01-28 13:51 UTC, tamjankowska requested changes

2021-01-28 13:51 UTC, tamjankowska commented on JakeyD11/index.html
Shall we get rid of some of this white space below?

2021-01-28 13:51 UTC, tamjankowska commented on JakeyD11/style.css
> +     color: pink;}
Maybe pop your closing curly on a new line?

2021-01-29 10:11 UTC, JakeyD11 commented on JakeyD11/index.html
done

2021-01-29 10:11 UTC, JakeyD11 commented on JakeyD11/style.css
> +     color: pink;}
done :)

2021-01-29 10:11 UTC, jadavey91 submitted a review, later dismissed
Cool

2021-01-29 10:12 UTC, boothscript requested changes
you have two closing html tags

2021-01-29 10:13 UTC, Edwine-R approved these changes

2021-01-29 10:13 UTC, JakeyD11 commented
> you have two closing html tags

done thanks

2021-01-29 10:15 UTC, boothscript approved these changes
Looks good

2021-01-29 10:23 UTC, jthomasw88 approved these changes
looks ok to me matey

2021-01-29 10:24 UTC, Edwine-R approved these changes

2021-01-29 10:25 UTC, merged