#1 Added name to authors
wearecodenation/master21-git101 pull request #22
Opened 2021-01-27 11:11 UTC by evanmorrisdev

Added my username and /1 to the authors page.

2021-01-27 11:52 UTC, johnmuir2001 reviewed
This looks good :)

2021-01-27 14:46 UTC, tamjankowska requested changes
Hey Evan, please could you put your full name here as opposed to your username :)

2021-01-28 12:19 UTC, SteIddon reviewed
all good

2021-01-28 15:18 UTC, ap42m approved these changes

2021-01-28 16:08 UTC, sarahnwright approved these changes

2021-01-28 16:14 UTC, johnmuir2001 approved these changes

2021-02-01 10:09 UTC, tamjankowska approved these changes

2021-02-01 10:13 UTC, merged