11 Using the footer html tag create a footer for your index page
wearecodenation/master21-git101 pull request #305
Opened 2021-01-30 17:01 UTC by nisharai26

2021-01-30 17:20 UTC, boothscript requested changes

2021-01-30 17:20 UTC, boothscript commented on nisharai26/songsIndex.html
>      </tbody>
There are two `</tbody>` tags that you don't need in your file.

2021-01-30 18:36 UTC, boothscript approved these changes
Great

2021-02-01 10:20 UTC, jthomasw88 approved these changes

2021-02-01 10:22 UTC, Melia-create approved these changes

2021-02-01 10:25 UTC, merged